# Generated by Django 4.1 on 2023-05-08 13:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reba', '0002_post_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reba',
            fields=[
                ('rebaID', models.IntegerField(primary_key=True, serialize=False)),
                ('neckPosition', models.CharField(max_length=30)),
                ('neckAdjust', models.CharField(max_length=30)),
                ('neckScore', models.IntegerField()),
                ('trunkPosition', models.CharField(max_length=30)),
                ('trunkAdjust', models.CharField(max_length=30)),
                ('trunkScore', models.IntegerField()),
                ('legPosition', models.CharField(max_length=30)),
                ('legScore', models.IntegerField()),
                ('postureScoreA', models.IntegerField()),
                ('flScore', models.IntegerField()),
                ('scoreA', models.IntegerField()),
                ('upperArmPosition', models.CharField(max_length=30)),
                ('upperArmAdjust', models.CharField(max_length=30)),
                ('upperArmScore', models.IntegerField()),
                ('lowerArmPosition', models.CharField(max_length=30)),
                ('lowerArmScore', models.IntegerField()),
                ('wristPosition', models.CharField(max_length=30)),
                ('wristAdjust', models.CharField(max_length=30)),
                ('wristScore', models.IntegerField()),
                ('postureScoreB', models.IntegerField()),
                ('couplingScore', models.IntegerField()),
                ('scoreB', models.IntegerField()),
                ('tableScoreC', models.IntegerField()),
                ('activityScore', models.IntegerField()),
                ('finalRebaScore', models.IntegerField()),
                ('userID', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
