# Generated by Django 4.1 on 2023-05-09 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reba', '0003_reba_delete_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='reba',
            name='legAdjust',
            field=models.CharField(default=3, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reba',
            name='legScore',
            field=models.IntegerField(default=0),
        ),
    ]
