# Generated by Django 4.1 on 2023-05-10 21:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reba', '0004_reba_legadjust_alter_reba_legscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reba',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
